name: Log User Input

on:
  push:
    paths:
      - 'main/user_log.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'main/.github/workflows'
        node-version: '20.x'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log User Info
      run: |
        echo '${{ github.event_name }}'
        echo 'Logging user info...'
        echo 'User input: ${{ secrets.USER_INPUT }}' >> user_log.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add user_log.txt
        git commit -m 'Log user input'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
